"""initial KittyBoom schema"""
from alembic import op
import sqlalchemy as sa
revision = "0001"
down_revision = None
def upgrade():
    op.create_table("roles", sa.Column("id", sa.Integer, primary_key=True), sa.Column("name", sa.String(30), unique=True, nullable=False))
    op.create_table("users", sa.Column("id", sa.Integer, primary_key=True), sa.Column("email", sa.String(255), unique=True, index=True, nullable=False), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("role_id", sa.Integer, sa.ForeignKey("roles.id"), nullable=False), sa.Column("is_active", sa.Boolean, server_default=sa.true()))
    op.create_table("categories", sa.Column("id", sa.Integer, primary_key=True), sa.Column("name", sa.String(80), unique=True, nullable=False), sa.Column("description", sa.Text), sa.Column("image_url", sa.String(500)), sa.Column("position", sa.Integer, server_default="0"), sa.Column("is_active", sa.Boolean, server_default=sa.true()))
    op.create_table("products", sa.Column("id", sa.Integer, primary_key=True), sa.Column("sku", sa.String(40), unique=True, nullable=False), sa.Column("name", sa.String(180), index=True, nullable=False), sa.Column("description", sa.Text, server_default=""), sa.Column("category_id", sa.Integer, sa.ForeignKey("categories.id"), nullable=False), sa.Column("cost_price", sa.Numeric(12,2)), sa.Column("price", sa.Numeric(12,2), nullable=False), sa.Column("sale_price", sa.Numeric(12,2)), sa.Column("material", sa.String(80)), sa.Column("color", sa.String(80)), sa.Column("stock", sa.Integer, server_default="0"), sa.Column("min_stock", sa.Integer, server_default="2"), sa.Column("is_active", sa.Boolean, server_default=sa.true()), sa.Column("is_new", sa.Boolean, server_default=sa.false()), sa.Column("is_featured", sa.Boolean, server_default=sa.false()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.CheckConstraint("stock >= 0"), sa.CheckConstraint("price >= 0"))
    op.create_table("customers", sa.Column("id", sa.Integer, primary_key=True), sa.Column("name", sa.String(180), nullable=False), sa.Column("phone", sa.String(30), index=True, nullable=False), sa.Column("email", sa.String(255)), sa.Column("address", sa.Text), sa.Column("instagram", sa.String(100)), sa.Column("notes", sa.Text))
    op.create_table("orders", sa.Column("id", sa.Integer, primary_key=True), sa.Column("number", sa.String(30), unique=True, nullable=False), sa.Column("customer_id", sa.Integer, sa.ForeignKey("customers.id"), nullable=False), sa.Column("status", sa.String(30), server_default="pending"), sa.Column("payment_method", sa.String(30), server_default="cash"), sa.Column("payment_status", sa.String(30), server_default="pending"), sa.Column("delivery_method", sa.String(80)), sa.Column("address", sa.Text), sa.Column("notes", sa.Text), sa.Column("total", sa.Numeric(12,2), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("order_items", sa.Column("id", sa.Integer, primary_key=True), sa.Column("order_id", sa.Integer, sa.ForeignKey("orders.id"), nullable=False), sa.Column("product_id", sa.Integer, sa.ForeignKey("products.id"), nullable=False), sa.Column("product_name", sa.String(180), nullable=False), sa.Column("quantity", sa.Integer, nullable=False), sa.Column("unit_price", sa.Numeric(12,2), nullable=False), sa.Column("subtotal", sa.Numeric(12,2), nullable=False), sa.CheckConstraint("quantity > 0"))
    op.create_table("product_images", sa.Column("id", sa.Integer, primary_key=True), sa.Column("product_id", sa.Integer, sa.ForeignKey("products.id"), nullable=False), sa.Column("url", sa.String(500), nullable=False), sa.Column("filename", sa.String(255), nullable=False), sa.Column("mime_type", sa.String(60)), sa.Column("size", sa.Integer), sa.Column("position", sa.Integer, server_default="0"), sa.Column("is_primary", sa.Boolean, server_default=sa.false()))
    op.create_table("product_variants", sa.Column("id", sa.Integer, primary_key=True), sa.Column("product_id", sa.Integer, sa.ForeignKey("products.id"), nullable=False), sa.Column("name", sa.String(120), nullable=False), sa.Column("sku", sa.String(50), unique=True), sa.Column("stock", sa.Integer, server_default="0"), sa.Column("price_delta", sa.Numeric(12,2), server_default="0"), sa.CheckConstraint("stock >= 0"))
    op.create_table("inventory_movements", sa.Column("id", sa.Integer, primary_key=True), sa.Column("product_id", sa.Integer, sa.ForeignKey("products.id"), nullable=False), sa.Column("quantity", sa.Integer, nullable=False), sa.Column("movement_type", sa.String(30), nullable=False), sa.Column("reason", sa.Text, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("business_settings", sa.Column("id", sa.Integer, primary_key=True), sa.Column("business_name", sa.String(120), server_default="KittyBoom"), sa.Column("whatsapp", sa.String(30)), sa.Column("instagram", sa.String(120)), sa.Column("tiktok", sa.String(120)), sa.Column("address", sa.Text), sa.Column("hours", sa.Text), sa.Column("currency", sa.String(5), server_default="S/"), sa.Column("logo_url", sa.String(500)))
    op.create_table("banners", sa.Column("id", sa.Integer, primary_key=True), sa.Column("title", sa.String(180), nullable=False), sa.Column("subtitle", sa.Text), sa.Column("image_url", sa.String(500)), sa.Column("is_active", sa.Boolean, server_default=sa.true()))
    op.create_table("audit_logs", sa.Column("id", sa.Integer, primary_key=True), sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id")), sa.Column("action", sa.String(100), nullable=False), sa.Column("entity", sa.String(80), nullable=False), sa.Column("entity_id", sa.String(50)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
def downgrade():
    for table in ["audit_logs","banners","business_settings","inventory_movements","product_variants","product_images","order_items","orders","customers","products","categories","users","roles"]: op.drop_table(table)

