from datetime import datetime
from decimal import Decimal
from sqlalchemy import String, Text, Integer, Boolean, Numeric, ForeignKey, DateTime, CheckConstraint, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base import Base
class Role(Base):
    __tablename__="roles"; id: Mapped[int]=mapped_column(primary_key=True); name: Mapped[str]=mapped_column(String(30), unique=True)
class User(Base):
    __tablename__="users"; id: Mapped[int]=mapped_column(primary_key=True); email: Mapped[str]=mapped_column(String(255), unique=True, index=True); password_hash: Mapped[str]=mapped_column(String(255)); role_id: Mapped[int]=mapped_column(ForeignKey("roles.id")); is_active: Mapped[bool]=mapped_column(default=True); role: Mapped[Role]=relationship()
class Category(Base):
    __tablename__="categories"; id: Mapped[int]=mapped_column(primary_key=True); name: Mapped[str]=mapped_column(String(80), unique=True); description: Mapped[str|None]=mapped_column(Text); image_url: Mapped[str|None]=mapped_column(String(500)); position: Mapped[int]=mapped_column(default=0); is_active: Mapped[bool]=mapped_column(default=True)
class Product(Base):
    __tablename__="products"; __table_args__=(CheckConstraint("stock >= 0"),)
    id: Mapped[int]=mapped_column(primary_key=True); sku: Mapped[str]=mapped_column(String(40), unique=True); name: Mapped[str]=mapped_column(String(180), index=True); description: Mapped[str]=mapped_column(Text, default=""); category_id: Mapped[int]=mapped_column(ForeignKey("categories.id")); cost_price: Mapped[Decimal|None]=mapped_column(Numeric(12,2)); price: Mapped[Decimal]=mapped_column(Numeric(12,2)); sale_price: Mapped[Decimal|None]=mapped_column(Numeric(12,2)); material: Mapped[str|None]=mapped_column(String(80)); color: Mapped[str|None]=mapped_column(String(80)); stock: Mapped[int]=mapped_column(default=0); min_stock: Mapped[int]=mapped_column(default=2); has_variants: Mapped[bool]=mapped_column(default=False); is_active: Mapped[bool]=mapped_column(default=True); is_new: Mapped[bool]=mapped_column(default=False); is_featured: Mapped[bool]=mapped_column(default=False); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), server_default=func.now()); category: Mapped[Category]=relationship(); images: Mapped[list["ProductImage"]]=relationship(order_by="ProductImage.position",cascade="all, delete-orphan"); variants: Mapped[list["ProductVariant"]]=relationship(order_by="ProductVariant.position",cascade="all, delete-orphan")
    @property
    def primary_image_url(self):
        if not self.images: return None
        return next((image.url for image in self.images if image.is_primary),self.images[0].url)
class Customer(Base):
    __tablename__="customers"; id: Mapped[int]=mapped_column(primary_key=True); name: Mapped[str]=mapped_column(String(180)); phone: Mapped[str]=mapped_column(String(30), index=True); email: Mapped[str|None]=mapped_column(String(255)); address: Mapped[str|None]=mapped_column(Text); instagram: Mapped[str|None]=mapped_column(String(100)); notes: Mapped[str|None]=mapped_column(Text)
class Order(Base):
    __tablename__="orders"; __table_args__=(CheckConstraint("status IN ('pending','finalized','cancelled')",name="ck_orders_status_simplified"),); id: Mapped[int]=mapped_column(primary_key=True); number: Mapped[str]=mapped_column(String(30), unique=True); customer_id: Mapped[int]=mapped_column(ForeignKey("customers.id")); status: Mapped[str]=mapped_column(String(30), default="pending"); payment_method: Mapped[str]=mapped_column(String(30), default="cash"); payment_status: Mapped[str]=mapped_column(String(30), default="pending"); paid_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); sales_channel: Mapped[str]=mapped_column(String(30),default="web"); idempotency_key: Mapped[str|None]=mapped_column(String(80),unique=True); delivery_method: Mapped[str|None]=mapped_column(String(80)); address: Mapped[str|None]=mapped_column(Text); notes: Mapped[str|None]=mapped_column(Text); total: Mapped[Decimal]=mapped_column(Numeric(12,2)); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), server_default=func.now()); items: Mapped[list["OrderItem"]]=relationship(cascade="all, delete-orphan"); customer: Mapped[Customer]=relationship()
class OrderItem(Base):
    __tablename__="order_items"; id: Mapped[int]=mapped_column(primary_key=True); order_id: Mapped[int]=mapped_column(ForeignKey("orders.id")); product_id: Mapped[int]=mapped_column(ForeignKey("products.id")); variant_id: Mapped[int|None]=mapped_column(ForeignKey("product_variants.id")); product_name: Mapped[str]=mapped_column(String(180)); variant_name: Mapped[str|None]=mapped_column(String(120)); variant_sku: Mapped[str|None]=mapped_column(String(50)); variant_image_url: Mapped[str|None]=mapped_column(String(500)); quantity: Mapped[int]=mapped_column(); unit_price: Mapped[Decimal]=mapped_column(Numeric(12,2)); subtotal: Mapped[Decimal]=mapped_column(Numeric(12,2))
class ProductImage(Base):
    __tablename__="product_images"; id: Mapped[int]=mapped_column(primary_key=True); product_id: Mapped[int]=mapped_column(ForeignKey("products.id")); url: Mapped[str]=mapped_column(String(500)); filename: Mapped[str]=mapped_column(String(255)); mime_type: Mapped[str|None]=mapped_column(String(60)); size: Mapped[int|None]=mapped_column(); position: Mapped[int]=mapped_column(default=0); is_primary: Mapped[bool]=mapped_column(default=False)
class ProductVariant(Base):
    __tablename__="product_variants"; __table_args__=(CheckConstraint("stock >= 0"),)
    id: Mapped[int]=mapped_column(primary_key=True); product_id: Mapped[int]=mapped_column(ForeignKey("products.id")); name: Mapped[str]=mapped_column(String(120)); sku: Mapped[str|None]=mapped_column(String(50),unique=True); color: Mapped[str|None]=mapped_column(String(80)); size: Mapped[str|None]=mapped_column(String(80)); model: Mapped[str|None]=mapped_column(String(80)); finish: Mapped[str|None]=mapped_column(String(80)); price: Mapped[Decimal|None]=mapped_column(Numeric(12,2)); stock: Mapped[int]=mapped_column(default=0); min_stock: Mapped[int]=mapped_column(default=2); is_active: Mapped[bool]=mapped_column(default=True); image_url: Mapped[str|None]=mapped_column(String(500)); position: Mapped[int]=mapped_column(default=0); price_delta: Mapped[Decimal]=mapped_column(Numeric(12,2),default=0)
class InventoryMovement(Base):
    __tablename__="inventory_movements"; id: Mapped[int]=mapped_column(primary_key=True); product_id: Mapped[int]=mapped_column(ForeignKey("products.id")); variant_id: Mapped[int|None]=mapped_column(ForeignKey("product_variants.id")); quantity: Mapped[int]=mapped_column(); movement_type: Mapped[str]=mapped_column(String(30)); reason: Mapped[str]=mapped_column(Text); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class BusinessSettings(Base):
    __tablename__="business_settings"; id: Mapped[int]=mapped_column(primary_key=True); business_name: Mapped[str]=mapped_column(String(120),default="KittyBoom"); whatsapp: Mapped[str|None]=mapped_column(String(30)); instagram: Mapped[str|None]=mapped_column(String(120)); tiktok: Mapped[str|None]=mapped_column(String(120)); address: Mapped[str|None]=mapped_column(Text); hours: Mapped[str|None]=mapped_column(Text); currency: Mapped[str]=mapped_column(String(5),default="S/"); logo_url: Mapped[str|None]=mapped_column(String(500))
class Banner(Base):
    __tablename__="banners"; id: Mapped[int]=mapped_column(primary_key=True); title: Mapped[str]=mapped_column(String(180),default="Portada"); subtitle: Mapped[str|None]=mapped_column(Text); image_url: Mapped[str|None]=mapped_column(String(500)); filename: Mapped[str|None]=mapped_column(String(255)); mime_type: Mapped[str|None]=mapped_column(String(60)); size: Mapped[int|None]=mapped_column(); alt_text: Mapped[str]=mapped_column(String(255),default="Portada de KittyBoom"); position: Mapped[int]=mapped_column(default=0); is_primary: Mapped[bool]=mapped_column(default=False); is_active: Mapped[bool]=mapped_column(default=True)
class AuditLog(Base):
    __tablename__="audit_logs"; id: Mapped[int]=mapped_column(primary_key=True); user_id: Mapped[int|None]=mapped_column(ForeignKey("users.id")); action: Mapped[str]=mapped_column(String(100)); entity: Mapped[str]=mapped_column(String(80)); entity_id: Mapped[str|None]=mapped_column(String(50)); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class Purchase(Base):
    __tablename__="purchases"; id: Mapped[int]=mapped_column(primary_key=True); number: Mapped[str]=mapped_column(String(30),unique=True); supplier: Mapped[str|None]=mapped_column(String(180)); receipt_number: Mapped[str|None]=mapped_column(String(100)); total: Mapped[Decimal]=mapped_column(Numeric(12,2)); payment_method: Mapped[str]=mapped_column(String(30)); notes: Mapped[str|None]=mapped_column(Text); user_id: Mapped[int]=mapped_column(ForeignKey("users.id")); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); items: Mapped[list["PurchaseItem"]]=relationship(cascade="all, delete-orphan")
class PurchaseItem(Base):
    __tablename__="purchase_items"; id: Mapped[int]=mapped_column(primary_key=True); purchase_id: Mapped[int]=mapped_column(ForeignKey("purchases.id")); product_id: Mapped[int]=mapped_column(ForeignKey("products.id")); variant_id: Mapped[int|None]=mapped_column(ForeignKey("product_variants.id")); quantity: Mapped[int]=mapped_column(); unit_cost: Mapped[Decimal]=mapped_column(Numeric(12,2)); subtotal: Mapped[Decimal]=mapped_column(Numeric(12,2))
class CashMovement(Base):
    __tablename__="cash_movements"; __table_args__=(CheckConstraint("amount > 0",name="ck_cash_movement_amount_positive"),); id: Mapped[int]=mapped_column(primary_key=True); movement_type: Mapped[str]=mapped_column(String(40)); direction: Mapped[str]=mapped_column(String(10)); amount: Mapped[Decimal]=mapped_column(Numeric(12,2)); description: Mapped[str]=mapped_column(String(255)); payment_method: Mapped[str]=mapped_column(String(30)); order_id: Mapped[int|None]=mapped_column(ForeignKey("orders.id")); purchase_id: Mapped[int|None]=mapped_column(ForeignKey("purchases.id")); user_id: Mapped[int|None]=mapped_column(ForeignKey("users.id")); notes: Mapped[str|None]=mapped_column(Text); idempotency_key: Mapped[str|None]=mapped_column(String(100),unique=True); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
