import React, { useCallback, useEffect, useState } from 'react';
import { ChartNoAxesCombined, FolderTree, Landmark, LogOut, Package, Settings, ShoppingBag, Users, Warehouse } from 'lucide-react';
import ProductImagePicker, { type ExistingImage, type PendingImage } from './product-image-picker';
import { isPendingOrder, orderStatusLabel, paymentMethodLabel } from './order-status';
import OrdersAdmin from './orders-admin';
import CashAdmin from './cash-admin';
import BannerAdmin from './banner-admin';
import {API_URL}from'./config';

const API = API_URL;
type Row = Record<string, any>;
const field = 'w-full rounded-xl border border-black/10 px-4 py-3 outline-none focus:border-[#d9909f]';

export async function adminApi(path: string, options: RequestInit = {}) {
  const headers = new Headers(options.headers); const token = localStorage.getItem('kb_token');
  if (token) headers.set('Authorization', `Bearer ${token}`);
  if (options.body && !(options.body instanceof FormData)) headers.set('Content-Type', 'application/json');
  const response = await fetch(`${API}${path}`, { ...options, headers });
  if (response.status === 204) return null;
  const data = await response.json().catch(() => ({ detail: 'Error inesperado' }));
  if (!response.ok) throw new Error(data.detail || 'No se pudo completar la operación');
  return data;
}

function Head({ title, action, run }: { title: string; action?: string; run?: () => void }) {
  return <div className="mb-6 flex items-center justify-between"><h2 className="serif text-3xl">{title}</h2>{action && <button onClick={run} className="rounded-full bg-[#231f20] px-5 py-3 text-white">{action}</button>}</div>;
}
function Table({ heads, rows }: { heads: string[]; rows: React.ReactNode[][] }) {
  return <div className="overflow-x-auto rounded-2xl bg-white soft-shadow"><table className="w-full text-left text-sm"><thead><tr className="border-b text-gray-500">{heads.map(h => <th key={h} className="p-4">{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i} className="border-b last:border-0">{row.map((cell, j) => <td key={j} className="p-4">{cell}</td>)}</tr>)}</tbody></table></div>;
}
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) {
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4"><div className="max-h-[94vh] w-full max-w-3xl overflow-auto rounded-3xl bg-white p-6 soft-shadow"><div className="flex justify-between"><h2 className="serif text-2xl">{title}</h2><button onClick={close} aria-label="Cerrar">✕</button></div>{children}</div></div>;
}
function VariantManager({product,reload}:{product:Row;reload:()=>void}){const[editing,setEditing]=useState<Row|null>(null);const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget);const body={name:f.get('name'),sku:f.get('sku'),color:f.get('color')||null,size:f.get('size')||null,model:f.get('model')||null,finish:f.get('finish')||null,price:f.get('price')?Number(f.get('price')):null,stock:Number(f.get('stock')),min_stock:Number(f.get('min_stock')),is_active:f.get('is_active')==='on',image_url:f.get('image_url')||null,position:Number(f.get('position'))};await adminApi(editing.id?`/admin/products/${product.id}/variants/${editing.id}`:`/admin/products/${product.id}/variants`,{method:editing.id?'PUT':'POST',body:JSON.stringify(body)});setEditing(null);reload()};return <div className="sm:col-span-2 rounded-2xl border p-4"><div className="flex justify-between"><h3 className="font-semibold">Variantes del producto</h3><button type="button" onClick={()=>setEditing({is_active:true,stock:0,min_stock:2,position:(product.variants||[]).length})} className="rounded-full border px-4">Agregar variante</button></div><p className="text-xs text-gray-500">Stock activo total: {(product.variants||[]).filter((v:Row)=>v.is_active).reduce((s:number,v:Row)=>s+v.stock,0)}</p>{(product.variants||[]).map((v:Row)=><div key={v.id} className="mt-2 grid grid-cols-4 border-t pt-2 text-sm"><span>{v.sku}</span><span>{v.name}</span><span>{v.price?`S/ ${v.price}`:'Precio base'} · Stock {v.stock}</span><button type="button" onClick={()=>setEditing(v)} className="underline">Editar</button></div>)}{editing&&<form onSubmit={save} className="mt-4 grid gap-2 sm:grid-cols-3">{[['name','Nombre'],['sku','SKU único'],['color','Color'],['size','Talla'],['model','Modelo'],['finish','Acabado'],['image_url','URL de imagen']].map(([name,label])=><input key={name} className={field} name={name} defaultValue={editing[name]} placeholder={label} required={name==='name'||name==='sku'}/>)}<input className={field} name="price" type="number" min=".01" step=".01" defaultValue={editing.price} placeholder="Precio propio"/><input className={field} name="stock" type="number" min="0" defaultValue={editing.stock}/><input className={field} name="min_stock" type="number" min="0" defaultValue={editing.min_stock}/><input className={field} name="position" type="number" defaultValue={editing.position}/><label><input name="is_active" type="checkbox" defaultChecked={editing.is_active}/> Activa</label><div className="flex gap-2"><button className="rounded-full bg-[#231f20] px-4 py-2 text-white">Guardar</button><button type="button" onClick={()=>setEditing(null)}>Cancelar</button></div></form>}</div>}

function ProductEditor({ product, categories, close, saved }: { product: Row; categories: Row[]; close: () => void; saved: () => void }) {
  const [existing, setExisting] = useState<ExistingImage[]>([]); const [pending, setPending] = useState<PendingImage[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const loadImages = useCallback(async () => { if (product.id) setExisting(await adminApi(`/admin/products/${product.id}/images`)); }, [product.id]);
  useEffect(() => { void loadImages(); }, [loadImages]);
  const uploadImages = async (productId: number) => {
    for (const item of pending) {
      setPending(items => items.map(x => x.id === item.id ? { ...x, status: 'uploading', error: undefined } : x));
      try {
        const form = new FormData(); form.append('file', item.file);
        await adminApi(`/admin/products/${productId}/images?is_primary=${item.primary}`, { method: 'POST', body: form });
        if (item.replaceId) await adminApi(`/admin/products/${productId}/images/${item.replaceId}`, { method: 'DELETE' });
        setPending(items => items.map(x => x.id === item.id ? { ...x, status: 'uploaded' } : x));
      } catch (reason) {
        setPending(items => items.map(x => x.id === item.id ? { ...x, status: 'error', error: (reason as Error).message } : x)); throw reason;
      }
    }
  };
  const save = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setSaving(true); setError(''); const f = new FormData(event.currentTarget);
    const body = { name: f.get('name'), category_id: Number(f.get('category_id')), description: f.get('description'), price: Number(f.get('price')), sale_price: f.get('sale_price') ? Number(f.get('sale_price')) : null, material: f.get('material') || null, color: f.get('color') || null, stock: Number(f.get('stock')), min_stock: Number(f.get('min_stock')), has_variants:f.get('has_variants')==='on', is_new: f.get('is_new') === 'on', is_featured: f.get('is_featured') === 'on', ...(product.id ? { is_active: f.get('is_active') === 'on' } : {}) };
    if(!product.has_variants&&body.has_variants&&Number(body.stock)>0&&!confirm('Este producto tiene stock general. Ese stock no se moverá automáticamente: distribúyelo explícitamente entre las variantes o crea las variantes inicialmente en cero. ¿Continuar?')){setSaving(false);return}
    try {
      const savedProduct = await adminApi(product.id ? `/admin/products/${product.id}` : '/admin/products', { method: product.id ? 'PUT' : 'POST', body: JSON.stringify(body) });
      await uploadImages(savedProduct.id); saved(); close();
    } catch (reason) { setError((reason as Error).message); } finally { setSaving(false); }
  };
  const removeExisting = async (image: ExistingImage) => { if (!confirm('¿Eliminar esta imagen del producto? Esta acción no se puede deshacer.')) return; await adminApi(`/admin/products/${product.id}/images/${image.id}`, { method: 'DELETE' }); await loadImages(); };
  const primaryExisting = async (image: ExistingImage) => { await adminApi(`/admin/products/${product.id}/images/${image.id}?is_primary=true`, { method: 'PATCH' }); await loadImages(); };
  return <Modal title={product.id?'Editar producto':'Nuevo producto'} close={close}><form onSubmit={save} className="mt-5 grid gap-4 sm:grid-cols-2"><input className={field} name="name" defaultValue={product.name} placeholder="Nombre" required/><select className={field} name="category_id" defaultValue={product.category_id} required><option value="">Categoría</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><textarea className={`${field} sm:col-span-2`} name="description" defaultValue={product.description} placeholder="Descripción"/><input className={field} name="price" type="number" min=".01" step=".01" defaultValue={product.price} placeholder="Precio" required/><input className={field} name="sale_price" type="number" step=".01" defaultValue={product.sale_price} placeholder="Oferta opcional"/><input className={field} name="material" defaultValue={product.material} placeholder="Material"/><input className={field} name="color" defaultValue={product.color} placeholder="Color"/><input className={field} name="stock" type="number" min="0" defaultValue={product.stock??0} required/><input className={field} name="min_stock" type="number" min="0" defaultValue={product.min_stock??2} required/><label><input name="has_variants" type="checkbox" defaultChecked={product.has_variants}/> Este producto tiene variantes</label><label><input name="is_new" type="checkbox" defaultChecked={product.is_new}/> Nuevo</label><label><input name="is_featured" type="checkbox" defaultChecked={product.is_featured}/> Destacado</label>{product.id&&<label><input name="is_active" type="checkbox" defaultChecked={product.is_active}/> Activo</label>}<ProductImagePicker existing={existing} pending={pending} setPending={setPending} onDeleteExisting={removeExisting} onPrimaryExisting={primaryExisting}/>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700 sm:col-span-2">{error}</p>}<button disabled={saving} className="rounded-full bg-[#231f20] p-3 text-white disabled:opacity-50 sm:col-span-2">{saving?'Guardando y subiendo imágenes…':'Guardar producto'}</button></form>{product.id&&product.has_variants&&<div className="mt-5"><VariantManager product={product} reload={saved}/></div>}</Modal>;
}

function Products({ categories }: { categories: Row[] }) {
  const [rows, setRows] = useState<Row[]>([]); const [edit, setEdit] = useState<Row | null>(null); const load = useCallback(() => { void adminApi('/admin/products').then(setRows); }, []); useEffect(load, [load]);
  return <section><Head title="Productos" action="Nuevo producto" run={() => setEdit({})} /><Table heads={['SKU', 'Producto', 'Precio', 'Stock', 'Estado', '']} rows={rows.map(p => [p.sku, p.name, `S/ ${Number(p.sale_price ?? p.price).toFixed(2)}`, p.stock, p.is_active ? 'Activo' : 'Inactivo', <button className="underline" onClick={() => setEdit(p)}>Editar</button>])} />{edit && <ProductEditor product={edit} categories={categories} close={() => setEdit(null)} saved={load} />}</section>;
}
function Categories({ rows, reload }: { rows: Row[]; reload: () => void }) {
  const [edit, setEdit] = useState<Row | null>(null); const save = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); if (!edit) return; const f = new FormData(e.currentTarget); const body = { name: f.get('name'), description: f.get('description') || null, image_url: null, position: Number(f.get('position')), is_active: f.get('is_active') === 'on' }; await adminApi(edit.id ? `/admin/categories/${edit.id}` : '/admin/categories', { method: edit.id ? 'PUT' : 'POST', body: JSON.stringify(body) }); setEdit(null); reload(); };
  return <section><Head title="Categorías" action="Nueva categoría" run={() => setEdit({ is_active: true })} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rows.map(c => <article key={c.id} className="rounded-2xl bg-white p-5 soft-shadow"><small>ORDEN {c.position}</small><h3 className="text-xl font-semibold">{c.name}</h3><p className="text-sm text-gray-500">{c.description || 'Sin descripción'}</p><button className="mt-4 underline" onClick={() => setEdit(c)}>Editar</button></article>)}</div>{edit && <Modal title="Categoría" close={() => setEdit(null)}><form onSubmit={save} className="mt-5 grid gap-4"><input className={field} name="name" defaultValue={edit.name} required /><textarea className={field} name="description" defaultValue={edit.description} /><input className={field} name="position" type="number" defaultValue={edit.position ?? 0} /><label><input name="is_active" type="checkbox" defaultChecked={edit.is_active} /> Activa</label><button className="rounded-full bg-[#231f20] p-3 text-white">Guardar</button></form></Modal>}</section>;
}
function Customers() { const [rows, setRows] = useState<Row[]>([]); const load = useCallback(() => { void adminApi('/admin/customers').then(setRows); }, []); useEffect(load, [load]); return <section><Head title="Clientes" /><Table heads={['Nombre', 'Teléfono', 'Correo', 'Dirección']} rows={rows.map(c => [c.name, c.phone, c.email || '—', c.address || '—'])} /></section>; }
function Orders() {
  const [rows,setRows]=useState<Row[]>([]); const [error,setError]=useState(''); const load=useCallback(()=>{void adminApi('/admin/orders').then(setRows)},[]); useEffect(load,[load]);
  const change=async(id:number,status:'finalized'|'cancelled')=>{const question=status==='finalized'?'¿Finalizar este pedido? Se descontará el stock de los productos.':'¿Cancelar este pedido? El stock no será modificado.';if(!confirm(question))return;setError('');try{await adminApi(`/admin/orders/${id}/status?new_status=${status}`,{method:'PATCH'});load()}catch(reason){setError((reason as Error).message)}};
  const badge=(status:string)=><span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${status==='finalized'?'bg-green-100 text-green-800':status==='cancelled'?'bg-gray-200 text-gray-700':'bg-amber-100 text-amber-800'}`}>{orderStatusLabel(status)}</span>;
  return <section><Head title="Pedidos" />{error&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Table heads={['Pedido','Total','Pago','Estado','Acciones']} rows={rows.map(order=>[order.number,`S/ ${Number(order.total).toFixed(2)}`,paymentMethodLabel(order.payment_method),badge(order.status),isPendingOrder(order.status)?<div className="flex flex-wrap gap-2"><button onClick={()=>change(order.id,'finalized')} className="rounded-full bg-green-600 px-4 py-2 text-xs font-semibold text-white hover:bg-green-700">Finalizar</button><button onClick={()=>change(order.id,'cancelled')} className="rounded-full bg-gray-200 px-4 py-2 text-xs font-semibold text-gray-800 hover:bg-gray-300">Cancelar</button></div>:<span className="text-xs text-gray-500">Sin acciones disponibles</span>])}/></section>;
}
function Inventory(){const[products,setProducts]=useState<Row[]>([]),[query,setQuery]=useState(''),[error,setError]=useState('');const load=useCallback(()=>{void adminApi('/admin/inventory').then(setProducts)},[]);useEffect(load,[load]);const rows=products.flatMap(p=>p.has_variants?(p.variants||[]).map((v:Row)=>({product:p,variant:v,stock:v.stock,min:v.min_stock,sku:v.sku,name:`${p.name} — ${v.name}`})):[{product:p,variant:null,stock:p.stock,min:p.min_stock,sku:p.sku,name:p.name}]).filter(x=>`${x.name} ${x.sku}`.toLowerCase().includes(query.toLowerCase()));const adjust=async(x:Row)=>{const raw=prompt(`Ajuste de stock para ${x.name}. Usa positivo para entrada o negativo para salida.`);if(raw===null)return;const quantity=Number(raw);const reason=prompt('Motivo del ajuste:');if(!Number.isInteger(quantity)||!quantity||!reason){setError('Cantidad entera y motivo son obligatorios.');return}try{await adminApi(`/admin/inventory/${x.product.id}/movements${x.variant?`?variant_id=${x.variant.id}`:''}`,{method:'POST',body:JSON.stringify({quantity,reason,movement_type:'adjustment'})});load()}catch(e){setError((e as Error).message)}};return <section><Head title="Inventario"/><input className={`${field} mb-4 max-w-lg`} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filtrar por producto, SKU o variante"/>{error&&<p className="mb-3 text-red-700">{error}</p>}<Table heads={['Producto / variante','SKU','Stock','Mínimo','Alerta','']} rows={rows.map(x=>[x.name,x.sku,x.stock,x.min,x.stock<=x.min?'Stock bajo':'Correcto',<button onClick={()=>void adjust(x)} className="underline">Ajustar</button>])}/></section>}
function Config() {
  const [data, setData] = useState<Row>({}); const [message, setMessage] = useState(''); useEffect(() => { void adminApi('/admin/settings').then(setData); }, []);
  const save = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const body = Object.fromEntries(['business_name', 'whatsapp', 'instagram', 'tiktok', 'address', 'hours', 'currency', 'logo_url'].map(k => [k, f.get(k) || null])); const updated = await adminApi('/admin/settings', { method: 'PUT', body: JSON.stringify(body) }); setData(updated); setMessage('Configuración guardada. La tienda ya usa el nuevo número.'); window.dispatchEvent(new Event('kittyboom:settings-updated')); };
  return <section><Head title="Configuración" /><form onSubmit={save} className="grid max-w-3xl gap-4 rounded-3xl bg-white p-6 soft-shadow sm:grid-cols-2">{[['business_name', 'Negocio'], ['whatsapp', 'WhatsApp'], ['instagram', 'Instagram'], ['tiktok', 'TikTok'], ['address', 'Dirección'], ['hours', 'Horarios'], ['currency', 'Moneda'], ['logo_url', 'Logo horizontal']].map(([name, label]) => <label key={name} className="text-sm">{label}<input className={`${field} mt-2`} name={name} defaultValue={data[name] ?? ''} placeholder={name==='logo_url'?'/kittyboom-logo-horizontal.png':''}/></label>)}{message && <p className="rounded-xl bg-green-50 p-3 text-sm text-green-700 sm:col-span-2">{message}</p>}<button className="rounded-full bg-[#231f20] p-3 text-white sm:col-span-2">Guardar configuración</button></form><BannerAdmin request={adminApi}/></section>;
}
function Dashboard({ go }: { go: (tab: string) => void }) { const [data,setData]=useState<Row>({});const [stats,setStats]=useState<Row>({});const [days,setDays]=useState(30);useEffect(()=>{void Promise.all([adminApi('/admin/dashboard'),adminApi(`/admin/analytics?days=${days}`)]).then(([a,b])=>{setData(a);setStats(b)})},[days]);const sales=stats.sales_by_day||[];const peak=Math.max(1,...sales.map((x:Row)=>Number(x.total)));return <><div className="flex items-center justify-between"><Head title="Resumen del negocio"/><select value={days} onChange={e=>setDays(Number(e.target.value))} className="rounded-xl border px-3 py-2"><option value="7">7 días</option><option value="30">30 días</option><option value="90">90 días</option></select></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[[Package,'Productos',data.total_products],[ShoppingBag,'Finalizados',stats.finalized_orders],[Landmark,'Resultado',`S/ ${Number(stats.result||0).toFixed(2)}`],[Users,'Ticket promedio',`S/ ${Number(stats.average_ticket||0).toFixed(2)}`]].map(([Icon,label,value])=><div key={String(label)} className="rounded-2xl bg-white p-6 soft-shadow"><Icon/><p className="mt-4 text-sm text-gray-500">{String(label)}</p><p className="text-3xl font-semibold">{String(value??'—')}</p></div>)}</div><div className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl bg-white p-6 soft-shadow"><h3 className="font-semibold">Ventas por día</h3><div className="mt-4 flex h-48 items-end gap-2 overflow-x-auto">{sales.map((x:Row)=><div key={x.date} title={`${x.date}: S/ ${x.total}`} style={{height:`${Math.max(6,Number(x.total)/peak*100)}%`}} className="min-w-4 flex-1 rounded-t bg-[#d9909f]"/>)}</div></article><article className="rounded-2xl bg-white p-6 soft-shadow"><h3 className="font-semibold">Productos más vendidos</h3>{(stats.top_products||[]).map((x:Row)=><div className="mt-3 flex justify-between border-b pb-2"><span>{x.name}</span><b>{x.quantity}</b></div>)}<div className="mt-5 grid grid-cols-2 gap-3 text-sm"><p>Ingresos<br/><b>{`S/ ${Number(stats.income||0).toFixed(2)}`}</b></p><p>Egresos<br/><b>{`S/ ${Number(stats.expense||0).toFixed(2)}`}</b></p></div></article></div><button onClick={()=>go('cash')} className="mt-6 rounded-full bg-[#231f20] px-5 py-3 text-white">Ver caja</button></>}

export default function AdminPanel() {
  const [logged, setLogged] = useState(!!localStorage.getItem('kb_token')); const [tab, setTab] = useState('dashboard'); const [categories, setCategories] = useState<Row[]>([]); const [email, setEmail] = useState('admin@kittyboom.pe'); const [password, setPassword] = useState('KittyBoom123!'); const loadCategories = useCallback(() => { void adminApi('/admin/categories').then(setCategories); }, []); useEffect(() => { if (logged) loadCategories(); }, [logged, loadCategories]);
  const login = async (e: React.FormEvent) => { e.preventDefault(); try { const data = await adminApi('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); localStorage.setItem('kb_token', data.access_token); setLogged(true); } catch (reason) { alert((reason as Error).message); } };
  if (!logged) return <main className="grid min-h-screen place-items-center bg-[#f5e9de] p-6"><form onSubmit={login} className="w-full max-w-sm rounded-3xl bg-white p-8 soft-shadow"><p className="serif text-center text-3xl">KittyBoom</p><input value={email} onChange={e => setEmail(e.target.value)} className={`${field} mt-6`} /><input type="password" value={password} onChange={e => setPassword(e.target.value)} className={`${field} mt-3`} /><button className="mt-5 w-full rounded-full bg-[#231f20] p-3 text-white">Ingresar</button></form></main>;
  const nav = [['dashboard', ChartNoAxesCombined, 'Resumen'], ['products', Package, 'Productos'], ['categories', FolderTree, 'Categorías'], ['inventory', Warehouse, 'Inventario'], ['orders', ShoppingBag, 'Pedidos'], ['cash', Landmark, 'Caja'], ['customers', Users, 'Clientes'], ['settings', Settings, 'Configuración']] as const;
  return <main className="min-h-screen bg-[#f8f4f1] md:grid md:grid-cols-[240px_1fr]"><aside className="bg-[#231f20] p-5 text-white"><img src="/kittyboom-logo.png" alt="KittyBoom" className="h-24 w-32 rounded-xl bg-[#fffaf7] object-contain" /><nav className="mt-8 grid grid-cols-2 gap-2 md:grid-cols-1">{nav.map(([id, Icon, label]) => <button key={id} onClick={() => setTab(id)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-left text-sm ${tab === id ? 'bg-white text-black' : 'text-white/70'}`}><Icon size={18} />{label}</button>)}</nav><button onClick={() => { localStorage.removeItem('kb_token'); setLogged(false); }} className="mt-8 flex gap-2 px-3 text-sm"><LogOut size={17} /> Salir</button></aside><div className="p-5 md:p-9"><div className="mx-auto max-w-7xl">{tab === 'dashboard' && <Dashboard go={setTab} />}{tab === 'products' && <Products categories={categories} />}{tab === 'categories' && <Categories rows={categories} reload={loadCategories} />}{tab === 'customers' && <Customers />}{tab === 'orders' && <OrdersAdmin request={adminApi} />}{tab === 'inventory' && <Inventory />}{tab === 'cash' && <CashAdmin request={adminApi} />}{tab === 'settings' && <Config />}</div></div></main>;
}
