import React,{useCallback,useEffect,useMemo,useState} from 'react';
import PurchaseForm from './purchase-form';
type Row=Record<string,any>;type Requester=(path:string,options?:RequestInit)=>Promise<any>;
export type PurchaseLine={product_id:number;quantity:number;unit_cost:number};
export type CashFilters={date_from:string;date_to:string;direction:string;movement_type:string;payment_method:string;user_id:string;order_number:string;search:string};
const emptyFilters:CashFilters={date_from:'',date_to:'',direction:'',movement_type:'',payment_method:'',user_id:'',order_number:'',search:''};
const field='w-full rounded-xl border border-black/10 px-3 py-2 outline-none focus:border-[#d9909f]';
const labels:Record<string,string>={sale_income:'Ingreso por venta',business_expense:'Gasto del negocio',manual_income:'Ingreso manual',initial_balance:'Saldo inicial',positive_adjustment:'Ajuste positivo',negative_adjustment:'Ajuste negativo',merchandise_purchase:'Compra de mercadería',cash:'Efectivo',yape:'Yape',plin:'Plin',transfer:'Transferencia',other:'Otro'};
const money=(value:any)=>`S/ ${Number(value||0).toFixed(2)}`;
export function movementQuery(filters:CashFilters,skip:number,limit=20){const params=new URLSearchParams({skip:String(skip),limit:String(limit)});Object.entries(filters).forEach(([key,value])=>{if(value)params.set(key,key==='date_to'?`${value}T23:59:59`:key==='date_from'?`${value}T00:00:00`:value)});return `/admin/cash/movements?${params}`}
export function addOrMergeLine(lines:PurchaseLine[],productId:number){const found=lines.find(x=>x.product_id===productId);return found?lines.map(x=>x.product_id===productId?{...x,quantity:x.quantity+1}:x):[...lines,{product_id:productId,quantity:1,unit_cost:0}]}

export default function CashAdmin({request}:{request:Requester}){
 const [summary,setSummary]=useState<Row>({});const [data,setData]=useState<Row>({items:[]});const [products,setProducts]=useState<Row[]>([]);const [mode,setMode]=useState<'movement'|'purchase'|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [filters,setFilters]=useState<CashFilters>(emptyFilters);const [applied,setApplied]=useState<CashFilters>(emptyFilters);const [skip,setSkip]=useState(0);const [searchProduct,setSearchProduct]=useState('');const [lines,setLines]=useState<PurchaseLine[]>([]);const limit=20;
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [s,m,p]=await Promise.all([request('/admin/cash/summary'),request(movementQuery(applied,skip,limit)),request('/admin/products')]);setSummary(s);setData(m);setProducts(p)}catch(reason){setError((reason as Error).message)}finally{setLoading(false)}},[request,applied,skip]);useEffect(()=>{void load()},[load]);
 const filteredProducts=useMemo(()=>{const q=searchProduct.trim().toLowerCase();return q?products.filter(p=>`${p.name} ${p.sku}`.toLowerCase().includes(q)).slice(0,8):[]},[products,searchProduct]);const total=lines.reduce((sum,line)=>sum+line.quantity*line.unit_cost,0);
 const movement=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError('');const f=new FormData(e.currentTarget);try{await request('/admin/cash/movements',{method:'POST',body:JSON.stringify({movement_type:f.get('movement_type'),amount:Number(f.get('amount')),description:f.get('description'),payment_method:f.get('payment_method'),reason:f.get('reason')||null})});setMode(null);await load()}catch(reason){setError((reason as Error).message)}finally{setSaving(false)}};
 const purchase=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');if(!lines.length||lines.some(x=>x.quantity<=0||x.unit_cost<=0)){setError('Agrega productos con cantidad y costo mayores que cero.');return}if(!confirm(`¿Registrar esta compra por ${money(total)}? Se aumentará el inventario de ${lines.length} producto(s).`))return;setSaving(true);const f=new FormData(e.currentTarget);try{await request('/admin/cash/purchases',{method:'POST',body:JSON.stringify({supplier:f.get('supplier')||null,receipt_number:f.get('receipt_number')||null,payment_method:f.get('payment_method'),notes:f.get('notes')||null,items:lines})});setLines([]);setMode(null);await load()}catch(reason){setError((reason as Error).message)}finally{setSaving(false)}};
 const applyFilters=(e:React.FormEvent)=>{e.preventDefault();setSkip(0);setApplied({...filters})};const clearFilters=()=>{setFilters(emptyFilters);setApplied(emptyFilters);setSkip(0)};
 return <section><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><h2 className="serif text-3xl">Caja</h2><div className="flex gap-2"><button onClick={()=>setMode('purchase')} className="rounded-full border px-4 py-2">Registrar compra</button><button onClick={()=>setMode('movement')} className="rounded-full bg-[#231f20] px-4 py-2 text-white">Registrar egreso o ingreso</button></div></div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Saldo actual',summary.balance],['Ingresos de hoy',summary.today_income],['Egresos de hoy',summary.today_expense],['Resultado del mes',summary.month_result]].map(([label,value])=><article key={label as string} className={`rounded-2xl bg-white p-5 soft-shadow ${label==='Saldo actual'&&Number(value)<0?'ring-2 ring-red-500':''}`}><p className="text-sm text-gray-500">{label}</p><strong className={Number(value)<0?'text-2xl text-red-700':'text-2xl'}>{money(value)}</strong></article>)}</div>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}
 {mode==='movement'&&<form onSubmit={movement} className="mt-5 grid gap-3 rounded-2xl bg-white p-5 sm:grid-cols-2"><select name="movement_type" className={field}>{['business_expense','manual_income','initial_balance','positive_adjustment','negative_adjustment'].map(x=><option key={x} value={x}>{labels[x]}</option>)}</select><input name="amount" className={field} type="number" min=".01" step=".01" placeholder="Monto" required/><input name="description" className={field} placeholder="Descripción" required/><select name="payment_method" className={field}>{['cash','yape','plin','transfer','other'].map(x=><option key={x} value={x}>{labels[x]}</option>)}</select><input name="reason" className={field} placeholder="Motivo (obligatorio para ajustes)"/><div className="flex gap-2"><button disabled={saving} className="rounded-full bg-[#231f20] px-5 py-2 text-white disabled:opacity-50">{saving?'Guardando…':'Guardar'}</button><button type="button" onClick={()=>setMode(null)}>Cerrar</button></div></form>}
 {mode==='purchase'&&<PurchaseForm products={products} request={request} cancel={()=>setMode(null)} done={async()=>{setMode(null);await load()}}/>}
 <form onSubmit={applyFilters} className="mt-6 grid gap-3 rounded-2xl bg-white p-4 sm:grid-cols-2 lg:grid-cols-4"><input type="date" aria-label="Fecha inicial" className={field} value={filters.date_from} onChange={e=>setFilters({...filters,date_from:e.target.value})}/><input type="date" aria-label="Fecha final" className={field} value={filters.date_to} onChange={e=>setFilters({...filters,date_to:e.target.value})}/><select aria-label="Ingreso o egreso" className={field} value={filters.direction} onChange={e=>setFilters({...filters,direction:e.target.value})}><option value="">Ingreso o egreso</option><option value="income">Ingreso</option><option value="expense">Egreso</option></select><select aria-label="Tipo de movimiento" className={field} value={filters.movement_type} onChange={e=>setFilters({...filters,movement_type:e.target.value})}><option value="">Todos los tipos</option>{Object.entries(labels).slice(0,7).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="Método de pago" className={field} value={filters.payment_method} onChange={e=>setFilters({...filters,payment_method:e.target.value})}><option value="">Todos los métodos</option>{['cash','yape','plin','transfer','other'].map(x=><option key={x} value={x}>{labels[x]}</option>)}</select><input className={field} inputMode="numeric" placeholder="ID de usuario" value={filters.user_id} onChange={e=>setFilters({...filters,user_id:e.target.value})}/><input className={field} placeholder="Número de pedido o referencia" value={filters.order_number} onChange={e=>setFilters({...filters,order_number:e.target.value})}/><input className={field} placeholder="Buscar en concepto" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><div className="flex gap-2"><button className="rounded-full bg-[#231f20] px-4 py-2 text-white">Aplicar filtros</button><button type="button" onClick={clearFilters} className="rounded-full border px-4 py-2">Limpiar filtros</button></div></form>
 <div className="mt-4 overflow-x-auto rounded-2xl bg-white"><table className="w-full text-left text-sm"><thead><tr>{['Fecha','Concepto','Método','Ingreso','Egreso','Saldo','Referencia','Usuario'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{data.items?.map((m:Row)=><tr key={m.id} className="border-t"><td className="p-3">{new Date(m.created_at).toLocaleString('es-PE')}</td><td className="p-3">{m.description}</td><td className="p-3">{labels[m.payment_method]||'—'}</td><td className="p-3 font-medium text-green-700">{m.direction==='income'?money(m.amount):'—'}</td><td className="p-3 font-medium text-red-700">{m.direction==='expense'?money(m.amount):'—'}</td><td className="p-3 font-semibold">{money(m.balance)}</td><td className="p-3">{m.order_number||(m.purchase_id?`Compra #${m.purchase_id}`:'—')}</td><td className="p-3">{m.user||m.user_id||'Automático'}</td></tr>)}</tbody></table>{!loading&&!data.items?.length&&<p className="p-8 text-center text-gray-500">No se encontraron movimientos con estos filtros.</p>}{loading&&<p className="p-8 text-center text-gray-500">Cargando movimientos…</p>}</div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><button disabled={!skip||loading} onClick={()=>setSkip(Math.max(0,skip-limit))}>← Anterior</button><span>{data.total||0} resultado(s) · Página {Math.floor(skip/limit)+1} de {Math.max(1,Math.ceil((data.total||0)/limit))}</span><button disabled={skip+limit>=(data.total||0)||loading} onClick={()=>setSkip(skip+limit)}>Siguiente →</button></div></section>
}
