import React,{useEffect,useRef,useState}from'react';import{ChevronLeft,ChevronRight}from'lucide-react';
export type HeroImage={id:number|string;image_url:string;alt_text?:string;position?:number;is_primary?:boolean};
export const prepareHeroImages=(images:HeroImage[])=>[...new Map(images.map(x=>[x.image_url,x])).values()].sort((a,b)=>Number(Boolean(b.is_primary))-Number(Boolean(a.is_primary))||(a.position??0)-(b.position??0));
export const heroNext=(i:number,n:number)=>(i+1)%Math.max(1,n);export const heroPrevious=(i:number,n:number)=>(i-1+Math.max(1,n))%Math.max(1,n);export const heroSwipe=(start:number,end:number,i:number,n:number)=>Math.abs(start-end)<40?i:start>end?heroNext(i,n):heroPrevious(i,n);
export default function HeroCarousel({images,backendOrigin=''}:{images:HeroImage[];backendOrigin?:string}){
 const items=prepareHeroImages(images),[index,setIndex]=useState(0),[paused,setPaused]=useState(false),[reduced,setReduced]=useState(false),touch=useRef(0);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(media.matches);update();media.addEventListener?.('change',update);return()=>media.removeEventListener?.('change',update)},[]);
 useEffect(()=>{if(items.length<2||paused||reduced)return;const timer=window.setInterval(()=>setIndex(i=>heroNext(i,items.length)),5000);return()=>window.clearInterval(timer)},[items.length,paused,reduced,index]);
 if(!items.length)return <div className="grid aspect-[4/5] w-full place-items-center rounded-[12rem_12rem_2rem_2rem] bg-gradient-to-b from-[#f3cfd5] to-[#f5e9de] text-[10rem]">✧</div>;
 const item=items[index],move=(next:number)=>setIndex(next);if(/^https?:\/\//i.test(item.image_url))backendOrigin='';
 return <div className="relative aspect-[4/5] w-full overflow-hidden rounded-[3rem] bg-[#f3cfd5] outline-none" tabIndex={0} aria-label="Portada de KittyBoom" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocus={()=>setPaused(true)} onBlur={()=>setPaused(false)} onTouchStart={e=>{touch.current=e.touches[0].clientX;setPaused(true)}} onTouchEnd={e=>{move(heroSwipe(touch.current,e.changedTouches[0].clientX,index,items.length));setPaused(false)}}><img key={item.id} src={`${backendOrigin}${item.image_url}`} alt={item.alt_text||'Portada de KittyBoom'} className="h-full w-full object-cover transition-opacity duration-300"/>{items.length>1&&<><button aria-label="Portada anterior" onClick={()=>move(heroPrevious(index,items.length))} className="absolute left-3 top-1/2 grid h-11 w-11 -translate-y-1/2 place-items-center rounded-full bg-white/85 shadow"><ChevronLeft/></button><button aria-label="Portada siguiente" onClick={()=>move(heroNext(index,items.length))} className="absolute right-3 top-1/2 grid h-11 w-11 -translate-y-1/2 place-items-center rounded-full bg-white/85 shadow"><ChevronRight/></button><div className="absolute bottom-4 left-1/2 flex -translate-x-1/2 gap-2">{items.map((x,i)=><button key={x.id} aria-label={`Mostrar portada ${i+1}`} onClick={()=>move(i)} className={`h-2.5 w-2.5 rounded-full ${i===index?'bg-[#231f20]':'bg-white/80'}`}/>)}</div></>}</div>
}
