import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ChevronLeft, ChevronRight, ImageOff } from 'lucide-react';

export type GalleryImage = { id: number | string; url: string; filename?: string; is_primary?: boolean; position?: number };
export const nextIndex = (index: number, length: number) => length ? (index + 1) % length : 0;
export const previousIndex = (index: number, length: number) => length ? (index - 1 + length) % length : 0;
export const selectIndex = (index: number, length: number) => Math.min(Math.max(index, 0), Math.max(length - 1, 0));
export const swipeIndex = (startX: number, endX: number, index: number, length: number, threshold = 45) => startX - endX > threshold ? nextIndex(index, length) : endX - startX > threshold ? previousIndex(index, length) : index;
export function prepareImages(images: GalleryImage[]) {
  const unique = [...new Map(images.filter(image => image.url).map(image => [image.url, image])).values()];
  return unique.sort((a, b) => Number(Boolean(b.is_primary)) - Number(Boolean(a.is_primary)) || (a.position ?? 0) - (b.position ?? 0));
}

export default function ProductCarousel({ images, productName, backendOrigin = '' }: { images: GalleryImage[]; productName: string; backendOrigin?: string }) {
  const ordered = useMemo(() => prepareImages(images), [images]); const [active, setActive] = useState(0); const [failed, setFailed] = useState<Set<string>>(new Set()); const touchStart = useRef<number | null>(null); const multiple = ordered.length > 1;
  useEffect(() => setActive(0), [ordered.map(image => image.url).join('|')]);
  const src = (url: string) => /^https?:\/\//.test(url) ? url : `${backendOrigin}${url}`;
  const keyDown = (event: React.KeyboardEvent) => { if (!multiple) return; if (event.key === 'ArrowRight') { event.preventDefault(); setActive(index => nextIndex(index, ordered.length)); } if (event.key === 'ArrowLeft') { event.preventDefault(); setActive(index => previousIndex(index, ordered.length)); } };
  const moveTouch = (endX: number) => { if (touchStart.current === null || !multiple) return; setActive(index => swipeIndex(touchStart.current!, endX, index, ordered.length)); touchStart.current = null; };
  if (!ordered.length) return <div className="grid aspect-[4/5] w-full place-items-center rounded-3xl bg-[#f5e9de] text-center text-[#9a776e]"><div><ImageOff className="mx-auto" size={42} /><p className="mt-3 text-sm">Imagen no disponible</p></div></div>;
  const current = ordered[active]; const currentFailed = failed.has(current.url);
  return <section aria-label={`Galería de ${productName}`} tabIndex={0} onKeyDown={keyDown} className="outline-none focus-visible:ring-2 focus-visible:ring-[#d9909f] focus-visible:ring-offset-4"><div className="relative aspect-[4/5] w-full overflow-hidden rounded-3xl bg-[#f5e9de] soft-shadow" onTouchStart={event => { touchStart.current = event.touches[0]?.clientX ?? null; }} onTouchEnd={event => moveTouch(event.changedTouches[0]?.clientX ?? 0)}>{currentFailed ? <div className="grid h-full place-items-center text-center text-[#9a776e]"><div><ImageOff className="mx-auto" size={42} /><p className="mt-3 text-sm">No pudimos cargar esta imagen</p></div></div> : <img key={current.url} src={src(current.url)} alt={`${productName} · imagen ${active + 1}`} onError={() => setFailed(previous => new Set(previous).add(current.url))} className="h-full w-full object-contain p-3 opacity-100 transition-opacity duration-200" />}{multiple && <><button type="button" aria-label="Imagen anterior" onClick={() => setActive(index => previousIndex(index, ordered.length))} className="absolute left-3 top-1/2 grid h-11 w-11 -translate-y-1/2 place-items-center rounded-full bg-white/90 text-[#231f20] shadow-lg backdrop-blur hover:bg-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#d9909f]"><ChevronLeft /></button><button type="button" aria-label="Imagen siguiente" onClick={() => setActive(index => nextIndex(index, ordered.length))} className="absolute right-3 top-1/2 grid h-11 w-11 -translate-y-1/2 place-items-center rounded-full bg-white/90 text-[#231f20] shadow-lg backdrop-blur hover:bg-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#d9909f]"><ChevronRight /></button><span aria-live="polite" className="absolute bottom-3 right-3 rounded-full bg-black/55 px-3 py-1 text-xs text-white">{active + 1} / {ordered.length}</span></>}</div>{multiple && <div className="mt-4 flex gap-3 overflow-x-auto pb-2" aria-label="Miniaturas del producto">{ordered.map((image, index) => <button key={image.url} type="button" aria-label={`Mostrar imagen ${index + 1}`} aria-current={index === active ? 'true' : undefined} onClick={() => setActive(selectIndex(index, ordered.length))} className={`h-20 w-20 shrink-0 overflow-hidden rounded-xl border-2 bg-[#f5e9de] p-1 transition ${index === active ? 'border-[#d9909f] ring-2 ring-[#f3cfd5]' : 'border-transparent opacity-70 hover:opacity-100'}`}><img src={src(image.url)} alt="" className="h-full w-full rounded-lg object-contain" /></button>)}</div>}</section>;
}
